name: CI
on: push
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        shell: bash
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
