name: CI
on: push
jobs:
  prod-check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
          run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
