name: CI
on: push
jobs:
  prod-check:
    runs-on: 'docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/var/www/html" -w /var/www/html laravelsail/php81-composer:latest composer install --ignore-platform-reqs'
