name: CI
on: push
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/var/www/html" -w /var/www/html laravelsail/php81-composer:latest composer install  -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
      - name: Set alias sail
        run: |
          shopt -s expand_aliases
          alias sail='./vendor/bin/sail '
      - name: Up Sail
        run: sail up -d
#      - name: Run test
#        run: sail test
